package com.topview.school.dao.school;

import java.util.List;

import com.topview.school.po.ScoreStatus;

public interface ScoreStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    int insert(ScoreStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    int insertSelective(ScoreStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    ScoreStatus selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    int updateByPrimaryKeySelective(ScoreStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    int updateByPrimaryKey(ScoreStatus record);
    
    int updateBySchoolIdSelective(ScoreStatus record);
    
    List<ScoreStatus> getStatusBySchoolId(String schoolId);
}