package com.topview.school.po;



import java.util.Date;

public class AppraiseTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.id
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.comment
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.create_time
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.school_id
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.name
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.type
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.max_word
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private Integer maxWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_template.max_star
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    private Integer maxStar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.id
     *
     * @return the value of t_sc_appraise_template.id
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.id
     *
     * @param id the value for t_sc_appraise_template.id
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.comment
     *
     * @return the value of t_sc_appraise_template.comment
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.comment
     *
     * @param comment the value for t_sc_appraise_template.comment
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.create_time
     *
     * @return the value of t_sc_appraise_template.create_time
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.create_time
     *
     * @param createTime the value for t_sc_appraise_template.create_time
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.school_id
     *
     * @return the value of t_sc_appraise_template.school_id
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.school_id
     *
     * @param schoolId the value for t_sc_appraise_template.school_id
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.name
     *
     * @return the value of t_sc_appraise_template.name
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.name
     *
     * @param name the value for t_sc_appraise_template.name
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.type
     *
     * @return the value of t_sc_appraise_template.type
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.type
     *
     * @param type the value for t_sc_appraise_template.type
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.max_word
     *
     * @return the value of t_sc_appraise_template.max_word
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public Integer getMaxWord() {
        return maxWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.max_word
     *
     * @param maxWord the value for t_sc_appraise_template.max_word
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setMaxWord(Integer maxWord) {
        this.maxWord = maxWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_template.max_star
     *
     * @return the value of t_sc_appraise_template.max_star
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public Integer getMaxStar() {
        return maxStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_template.max_star
     *
     * @param maxStar the value for t_sc_appraise_template.max_star
     *
     * @mbggenerated Mon Aug 03 19:33:22 CST 2015
     */
    public void setMaxStar(Integer maxStar) {
        this.maxStar = maxStar;
    }
}