package com.topview.school.po;

import java.util.Date;

public class Appraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.student_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.teacher_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.time
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.template_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.star
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.word
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.semester_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String semesterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.class_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.type
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise.stage
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    private String stage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.id
     *
     * @return the value of t_sc_appraise.id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.id
     *
     * @param id the value for t_sc_appraise.id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.student_id
     *
     * @return the value of t_sc_appraise.student_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.student_id
     *
     * @param studentId the value for t_sc_appraise.student_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.teacher_id
     *
     * @return the value of t_sc_appraise.teacher_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.teacher_id
     *
     * @param teacherId the value for t_sc_appraise.teacher_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.time
     *
     * @return the value of t_sc_appraise.time
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.time
     *
     * @param time the value for t_sc_appraise.time
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.template_id
     *
     * @return the value of t_sc_appraise.template_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.template_id
     *
     * @param templateId the value for t_sc_appraise.template_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.star
     *
     * @return the value of t_sc_appraise.star
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.star
     *
     * @param star the value for t_sc_appraise.star
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setStar(String star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.word
     *
     * @return the value of t_sc_appraise.word
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.word
     *
     * @param word the value for t_sc_appraise.word
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.semester_id
     *
     * @return the value of t_sc_appraise.semester_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getSemesterId() {
        return semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.semester_id
     *
     * @param semesterId the value for t_sc_appraise.semester_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setSemesterId(String semesterId) {
        this.semesterId = semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.class_id
     *
     * @return the value of t_sc_appraise.class_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.class_id
     *
     * @param classId the value for t_sc_appraise.class_id
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.type
     *
     * @return the value of t_sc_appraise.type
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.type
     *
     * @param type the value for t_sc_appraise.type
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise.stage
     *
     * @return the value of t_sc_appraise.stage
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise.stage
     *
     * @param stage the value for t_sc_appraise.stage
     *
     * @mbggenerated Sun Aug 30 20:52:07 CST 2015
     */
    public void setStage(String stage) {
        this.stage = stage;
    }
}