package com.topview.school.po;

import java.util.Date;

/**
 * 家长PO
 */
public class Parent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.id
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.name
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.sex
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.parentType
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String parenttype; //家长类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.mobile
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String mobile; //手机号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.IDCard
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String idcard; //学号？不知道用处

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.create_time
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private Date createTime; //创建时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.type
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private Integer type; //类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.password
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String password; //密码

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent.super_password
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    private String superPassword; //超级密码

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.id
     *
     * @return the value of t_sc_parent.id
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.id
     *
     * @param id the value for t_sc_parent.id
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.name
     *
     * @return the value of t_sc_parent.name
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.name
     *
     * @param name the value for t_sc_parent.name
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.sex
     *
     * @return the value of t_sc_parent.sex
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.sex
     *
     * @param sex the value for t_sc_parent.sex
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.parentType
     *
     * @return the value of t_sc_parent.parentType
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getParenttype() {
        return parenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.parentType
     *
     * @param parenttype the value for t_sc_parent.parentType
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setParenttype(String parenttype) {
        this.parenttype = parenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.mobile
     *
     * @return the value of t_sc_parent.mobile
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.mobile
     *
     * @param mobile the value for t_sc_parent.mobile
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.IDCard
     *
     * @return the value of t_sc_parent.IDCard
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.IDCard
     *
     * @param idcard the value for t_sc_parent.IDCard
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.create_time
     *
     * @return the value of t_sc_parent.create_time
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.create_time
     *
     * @param createTime the value for t_sc_parent.create_time
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.type
     *
     * @return the value of t_sc_parent.type
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.type
     *
     * @param type the value for t_sc_parent.type
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.password
     *
     * @return the value of t_sc_parent.password
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.password
     *
     * @param password the value for t_sc_parent.password
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent.super_password
     *
     * @return the value of t_sc_parent.super_password
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public String getSuperPassword() {
        return superPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent.super_password
     *
     * @param superPassword the value for t_sc_parent.super_password
     *
     * @mbggenerated Wed May 06 23:49:52 CST 2015
     */
    public void setSuperPassword(String superPassword) {
        this.superPassword = superPassword;
    }
}