package com.topview.message.dao;

import com.topview.message.po.Kind;


/**
 * @author hcdn
 * 消息的种类
 */
public interface KindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_kind
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_kind
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    int insert(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_kind
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    int insertSelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_kind
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    Kind selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_kind
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    int updateByPrimaryKeySelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_push_kind
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    int updateByPrimaryKey(Kind record);
}