package com.topview.multimedia.po;

public class HornUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn_user.horn_id
     *
     * @mbggenerated Thu Oct 13 17:13:29 CST 2016
     */
    private String hornId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn_user.user_id
     *
     * @mbggenerated Thu Oct 13 17:13:29 CST 2016
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn_user.horn_id
     *
     * @return the value of t_mutimedia_horn_user.horn_id
     *
     * @mbggenerated Thu Oct 13 17:13:29 CST 2016
     */
    public String getHornId() {
        return hornId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn_user.horn_id
     *
     * @param hornId the value for t_mutimedia_horn_user.horn_id
     *
     * @mbggenerated Thu Oct 13 17:13:29 CST 2016
     */
    public void setHornId(String hornId) {
        this.hornId = hornId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn_user.user_id
     *
     * @return the value of t_mutimedia_horn_user.user_id
     *
     * @mbggenerated Thu Oct 13 17:13:29 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn_user.user_id
     *
     * @param userId the value for t_mutimedia_horn_user.user_id
     *
     * @mbggenerated Thu Oct 13 17:13:29 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}