package com.topview.multimedia.po;

import java.util.Date;

public class Horn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn.id
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn.message
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn.begin_time
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn.end_time
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn.flag
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_horn.send_id
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    private String sendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn.id
     *
     * @return the value of t_mutimedia_horn.id
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn.id
     *
     * @param id the value for t_mutimedia_horn.id
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn.message
     *
     * @return the value of t_mutimedia_horn.message
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn.message
     *
     * @param message the value for t_mutimedia_horn.message
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn.begin_time
     *
     * @return the value of t_mutimedia_horn.begin_time
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn.begin_time
     *
     * @param beginTime the value for t_mutimedia_horn.begin_time
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn.end_time
     *
     * @return the value of t_mutimedia_horn.end_time
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn.end_time
     *
     * @param endTime the value for t_mutimedia_horn.end_time
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn.flag
     *
     * @return the value of t_mutimedia_horn.flag
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn.flag
     *
     * @param flag the value for t_mutimedia_horn.flag
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_horn.send_id
     *
     * @return the value of t_mutimedia_horn.send_id
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public String getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_horn.send_id
     *
     * @param sendId the value for t_mutimedia_horn.send_id
     *
     * @mbggenerated Wed Oct 19 17:00:52 CST 2016
     */
    public void setSendId(String sendId) {
        this.sendId = sendId;
    }
}