package com.topview.multimedia.po;

import java.util.Date;

public class MultimediaPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.ID
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.t_m_ID
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private String tMId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.name
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.description
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.comment
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.label
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.status
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.video_path
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private String videoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.upload_time
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_photo.sort
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.ID
     *
     * @return the value of t_mutimedia_photo.ID
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.ID
     *
     * @param id the value for t_mutimedia_photo.ID
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.t_m_ID
     *
     * @return the value of t_mutimedia_photo.t_m_ID
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.t_m_ID
     *
     * @param tMId the value for t_mutimedia_photo.t_m_ID
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.name
     *
     * @return the value of t_mutimedia_photo.name
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.name
     *
     * @param name the value for t_mutimedia_photo.name
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.description
     *
     * @return the value of t_mutimedia_photo.description
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.description
     *
     * @param description the value for t_mutimedia_photo.description
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.comment
     *
     * @return the value of t_mutimedia_photo.comment
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.comment
     *
     * @param comment the value for t_mutimedia_photo.comment
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.label
     *
     * @return the value of t_mutimedia_photo.label
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.label
     *
     * @param label the value for t_mutimedia_photo.label
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.status
     *
     * @return the value of t_mutimedia_photo.status
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.status
     *
     * @param status the value for t_mutimedia_photo.status
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.video_path
     *
     * @return the value of t_mutimedia_photo.video_path
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.video_path
     *
     * @param videoPath the value for t_mutimedia_photo.video_path
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.upload_time
     *
     * @return the value of t_mutimedia_photo.upload_time
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.upload_time
     *
     * @param uploadTime the value for t_mutimedia_photo.upload_time
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_photo.sort
     *
     * @return the value of t_mutimedia_photo.sort
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_photo.sort
     *
     * @param sort the value for t_mutimedia_photo.sort
     *
     * @mbggenerated Sat Jul 23 14:26:48 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}