package com.topview.multimedia.po;

import java.util.Date;

public class MultimediaRichText {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.ID
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.t_m_ID
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private String tMId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.create_time
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.status
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.type
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.title
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.subtitle
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.titlephoto
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private String titlephoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.summary
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.essence
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private Boolean essence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.top
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private Boolean top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.read_number
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private Integer readNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.context
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.ID
     *
     * @return the value of t_mutimedia_rich_text.ID
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.ID
     *
     * @param id the value for t_mutimedia_rich_text.ID
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.t_m_ID
     *
     * @return the value of t_mutimedia_rich_text.t_m_ID
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.t_m_ID
     *
     * @param tMId the value for t_mutimedia_rich_text.t_m_ID
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.create_time
     *
     * @return the value of t_mutimedia_rich_text.create_time
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.create_time
     *
     * @param createTime the value for t_mutimedia_rich_text.create_time
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.status
     *
     * @return the value of t_mutimedia_rich_text.status
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.status
     *
     * @param status the value for t_mutimedia_rich_text.status
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.type
     *
     * @return the value of t_mutimedia_rich_text.type
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.type
     *
     * @param type the value for t_mutimedia_rich_text.type
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.title
     *
     * @return the value of t_mutimedia_rich_text.title
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.title
     *
     * @param title the value for t_mutimedia_rich_text.title
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.subtitle
     *
     * @return the value of t_mutimedia_rich_text.subtitle
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.subtitle
     *
     * @param subtitle the value for t_mutimedia_rich_text.subtitle
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.titlephoto
     *
     * @return the value of t_mutimedia_rich_text.titlephoto
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public String getTitlephoto() {
        return titlephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.titlephoto
     *
     * @param titlephoto the value for t_mutimedia_rich_text.titlephoto
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setTitlephoto(String titlephoto) {
        this.titlephoto = titlephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.summary
     *
     * @return the value of t_mutimedia_rich_text.summary
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.summary
     *
     * @param summary the value for t_mutimedia_rich_text.summary
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.essence
     *
     * @return the value of t_mutimedia_rich_text.essence
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public Boolean getEssence() {
        return essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.essence
     *
     * @param essence the value for t_mutimedia_rich_text.essence
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setEssence(Boolean essence) {
        this.essence = essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.top
     *
     * @return the value of t_mutimedia_rich_text.top
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.top
     *
     * @param top the value for t_mutimedia_rich_text.top
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.read_number
     *
     * @return the value of t_mutimedia_rich_text.read_number
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public Integer getReadNumber() {
        return readNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.read_number
     *
     * @param readNumber the value for t_mutimedia_rich_text.read_number
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setReadNumber(Integer readNumber) {
        this.readNumber = readNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.context
     *
     * @return the value of t_mutimedia_rich_text.context
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.context
     *
     * @param context the value for t_mutimedia_rich_text.context
     *
     * @mbggenerated Thu Aug 04 18:52:36 CST 2016
     */
    public void setContext(String context) {
        this.context = context;
    }
}