package com.topview.multimedia.po;

import java.util.Date;
/**
 * 文章分类
 * 项目名称:com.topview.multimedia.po<br>
 * 
 * @author houwenjun<br>
 * 创建时间:Apr 11, 2015<br>
 */
public class MultimediaSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_section.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_section.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String tMId; //所属多媒体空间id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_section.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_section.name2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String name2; //信息板块名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_section.description2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String description2; //板块描述

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_section.icon
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String icon; //icon图标路径

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_section.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String type; //信息板块类型

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_section.ID
     *
     * @return the value of t_mutimedia_section.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_section.ID
     *
     * @param id the value for t_mutimedia_section.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_section.t_m_ID
     *
     * @return the value of t_mutimedia_section.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_section.t_m_ID
     *
     * @param tMId the value for t_mutimedia_section.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_section.create_time
     *
     * @return the value of t_mutimedia_section.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_section.create_time
     *
     * @param createTime the value for t_mutimedia_section.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_section.name2
     *
     * @return the value of t_mutimedia_section.name2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_section.name2
     *
     * @param name2 the value for t_mutimedia_section.name2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setName2(String name2) {
        this.name2 = name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_section.description2
     *
     * @return the value of t_mutimedia_section.description2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getDescription2() {
        return description2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_section.description2
     *
     * @param description2 the value for t_mutimedia_section.description2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setDescription2(String description2) {
        this.description2 = description2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_section.icon
     *
     * @return the value of t_mutimedia_section.icon
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_section.icon
     *
     * @param icon the value for t_mutimedia_section.icon
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_section.type
     *
     * @return the value of t_mutimedia_section.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_section.type
     *
     * @param type the value for t_mutimedia_section.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }
}