package com.topview.school.dao.feedback;

import java.util.List;
import java.util.Map;

import com.topview.school.po.RecordUrl;


public interface RecordUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_record_url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_record_url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    int insert(RecordUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_record_url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    int insertSelective(RecordUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_record_url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    RecordUrl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_record_url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    int updateByPrimaryKeySelective(RecordUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sc_record_url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    int updateByPrimaryKey(RecordUrl record);
    
    /**
     * @description 用于根据关键字查询其对应的URL的访问量
     * @param String key,即为关键字
     * @return	关键字对应的URL
     */
    String selectUrlByKey(String key);
    
    /**
     * @return 返回所有的数据库中的URL和关键字
     */
    List<RecordUrl> selectAllKeysAndUrl();
}