package com.topview.multimedia.po;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.id
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.t_m_ID
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private String tMId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.create_time
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.context
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.status
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.type
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.title
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.essence
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private Boolean essence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.top
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private Boolean top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_post.publisher_id
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    private String publisherId;

    private String publisherName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.id
     *
     * @return the value of t_mutimedia_post.id
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.id
     *
     * @param id the value for t_mutimedia_post.id
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.t_m_ID
     *
     * @return the value of t_mutimedia_post.t_m_ID
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.t_m_ID
     *
     * @param tMId the value for t_mutimedia_post.t_m_ID
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.create_time
     *
     * @return the value of t_mutimedia_post.create_time
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.create_time
     *
     * @param createTime the value for t_mutimedia_post.create_time
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.context
     *
     * @return the value of t_mutimedia_post.context
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.context
     *
     * @param context the value for t_mutimedia_post.context
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setContext(String context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.status
     *
     * @return the value of t_mutimedia_post.status
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.status
     *
     * @param status the value for t_mutimedia_post.status
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.type
     *
     * @return the value of t_mutimedia_post.type
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.type
     *
     * @param type the value for t_mutimedia_post.type
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.title
     *
     * @return the value of t_mutimedia_post.title
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.title
     *
     * @param title the value for t_mutimedia_post.title
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.essence
     *
     * @return the value of t_mutimedia_post.essence
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public Boolean getEssence() {
        return essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.essence
     *
     * @param essence the value for t_mutimedia_post.essence
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setEssence(Boolean essence) {
        this.essence = essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.top
     *
     * @return the value of t_mutimedia_post.top
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.top
     *
     * @param top the value for t_mutimedia_post.top
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_post.publisher_id
     *
     * @return the value of t_mutimedia_post.publisher_id
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public String getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_post.publisher_id
     *
     * @param publisherId the value for t_mutimedia_post.publisher_id
     *
     * @mbggenerated Tue Jul 21 00:13:24 CST 2015
     */
    public void setPublisherId(String publisherId) {
        this.publisherId = publisherId;
    }

	public String getPublisherName() {
		return publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}
}