package com.topview.school.dao.user;

import com.topview.school.po.UserSalt;

public interface UserSaltMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    int insert(UserSalt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    int insertSelective(UserSalt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    UserSalt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    int updateByPrimaryKeySelective(UserSalt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    int updateByPrimaryKey(UserSalt record);
    
    
    public UserSalt getSaltByUserId(String userId);
    
    
}