package com.topview.multimedia.po;

import java.util.Date;

public class MultimediaCollect {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_collect.id
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_collect.pointtype
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	private String pointtype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_collect.pointid
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	private String pointid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_collect.userid
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	private String userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_collect.creattime
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	private Date creattime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_mutimedia_collect.id
	 *
	 * @return the value of t_mutimedia_collect.id
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_mutimedia_collect.id
	 *
	 * @param id
	 *            the value for t_mutimedia_collect.id
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_mutimedia_collect.pointtype
	 *
	 * @return the value of t_mutimedia_collect.pointtype
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public String getPointtype() {
		return pointtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_mutimedia_collect.pointtype
	 *
	 * @param pointtype
	 *            the value for t_mutimedia_collect.pointtype
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public void setPointtype(String pointtype) {
		this.pointtype = pointtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_mutimedia_collect.pointid
	 *
	 * @return the value of t_mutimedia_collect.pointid
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public String getPointid() {
		return pointid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_mutimedia_collect.pointid
	 *
	 * @param pointid
	 *            the value for t_mutimedia_collect.pointid
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public void setPointid(String pointid) {
		this.pointid = pointid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_mutimedia_collect.userid
	 *
	 * @return the value of t_mutimedia_collect.userid
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_mutimedia_collect.userid
	 *
	 * @param userid
	 *            the value for t_mutimedia_collect.userid
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_mutimedia_collect.creattime
	 *
	 * @return the value of t_mutimedia_collect.creattime
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_mutimedia_collect.creattime
	 *
	 * @param creattime
	 *            the value for t_mutimedia_collect.creattime
	 *
	 * @mbggenerated Mon Jul 27 11:11:11 CST 2015
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}
}