package com.topview.message.po;

public class BaiduPush {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baidu_push.id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baidu_push.userId
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baidu_push.channelId
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baidu_push.deviceType
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String devicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baidu_push.t_push_key_id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String tPushKeyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baidu_push.id
     *
     * @return the value of t_baidu_push.id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baidu_push.id
     *
     * @param id the value for t_baidu_push.id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baidu_push.userId
     *
     * @return the value of t_baidu_push.userId
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baidu_push.userId
     *
     * @param userid the value for t_baidu_push.userId
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baidu_push.channelId
     *
     * @return the value of t_baidu_push.channelId
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baidu_push.channelId
     *
     * @param channelid the value for t_baidu_push.channelId
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baidu_push.deviceType
     *
     * @return the value of t_baidu_push.deviceType
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baidu_push.deviceType
     *
     * @param devicetype the value for t_baidu_push.deviceType
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void setDevicetype(String devicetype) {
        this.devicetype = devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baidu_push.t_push_key_id
     *
     * @return the value of t_baidu_push.t_push_key_id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String gettPushKeyId() {
        return tPushKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baidu_push.t_push_key_id
     *
     * @param tPushKeyId the value for t_baidu_push.t_push_key_id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void settPushKeyId(String tPushKeyId) {
        this.tPushKeyId = tPushKeyId;
    }
}