package com.topview.message.po;

import java.util.Date;

/**
 * @Description 信息po
 * @Author <wuyiliang 757210697@qq.com>
 * @Date 2016年1月9日 上午10:56:15
 * @CopyRight 2016 TopView Inc
 * @version V1.0
 */
public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.content
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private String content; //消息内容

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.send_time
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private Date sendTime; //发送时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.sms
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private Integer sms; //短信标志，1是短信，0非短信

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.sender_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private String senderId; //发送者id
    
    private String senderKidId;//发送者当前在线孩子id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.t_push_type_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private String tPushTypeId; //推送模块id:1 家园桥,2  我的短信,3  请假申请,4  成绩推送,5	 系统通知,6  学生评价
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.t_push_postbox_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private String tPushPostboxId; //消息类型id:1  文字,2	图片,3  语音,4  视频,5  文件
  

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_message.t_push_kind_id
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    private String tPushKindId;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.id
     *
     * @return the value of t_push_message.id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.id
     *
     * @param id the value for t_push_message.id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.content
     *
     * @return the value of t_push_message.content
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.content
     *
     * @param content the value for t_push_message.content
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.send_time
     *
     * @return the value of t_push_message.send_time
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.send_time
     *
     * @param sendTime the value for t_push_message.send_time
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.sms
     *
     * @return the value of t_push_message.sms
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public Integer getSms() {
        return sms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.sms
     *
     * @param sms the value for t_push_message.sms
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void setSms(Integer sms) {
        this.sms = sms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.sender_id
     *
     * @return the value of t_push_message.sender_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.sender_id
     *
     * @param senderId the value for t_push_message.sender_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getSenderKidId() {
		return senderKidId;
	}

	public void setSenderKidId(String senderKidId) {
		this.senderKidId = senderKidId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.t_push_type_id
     *
     * @return the value of t_push_message.t_push_type_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public String gettPushTypeId() {
        return tPushTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.t_push_type_id
     *
     * @param tPushTypeId the value for t_push_message.t_push_type_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void settPushTypeId(String tPushTypeId) {
        this.tPushTypeId = tPushTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.t_push_postbox_id
     *
     * @return the value of t_push_message.t_push_postbox_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public String gettPushPostboxId() {
        return tPushPostboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.t_push_postbox_id
     *
     * @param tPushPostboxId the value for t_push_message.t_push_postbox_id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void settPushPostboxId(String tPushPostboxId) {
        this.tPushPostboxId = tPushPostboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_message.t_push_kind_id
     *
     * @return the value of t_push_message.t_push_kind_id
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    public String gettPushKindId() {
        return tPushKindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_message.t_push_kind_id
     *
     * @param tPushKindId the value for t_push_message.t_push_kind_id
     *
     * @mbggenerated Wed May 11 17:50:32 CST 2016
     */
    public void settPushKindId(String tPushKindId) {
        this.tPushKindId = tPushKindId;
    }
    
	@Override
	public String toString() {
		return "Message [id=" + id + ", content=" + content + ", sendTime=" + sendTime + ", sms=" + sms + ", senderId="
				+ senderId + ", senderKidId=" + senderKidId + ", tPushTypeId=" + tPushTypeId + ", tPushPostboxId="
				+ tPushPostboxId + ", tPushKindId=" + tPushKindId + "]";
	}
    
}