package com.topview.message.po;

public class PushType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_type.id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_type.type
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_type.id
     *
     * @return the value of t_push_type.id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_type.id
     *
     * @param id the value for t_push_type.id
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_type.type
     *
     * @return the value of t_push_type.type
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_type.type
     *
     * @param type the value for t_push_type.type
     *
     * @mbggenerated Tue Dec 01 22:48:03 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }
}