package com.topview.multimedia.dao.base;

import java.util.List;
import java.util.Map;

/**
 * 
 * 项目名称：news<br>
 * 类名称：BaseDao <br>
 * 类描述： 基础dao层接口 <br>
 * 创建人：luozhangjie <br>
 * 创建时间：2015年3月12日 下午9:16:55 <br>
 * 修改人：luozhangjie<br>
 * 修改时间：2015年3月12日 下午9:16:55 <br>
 * 修改备注： <br>
 * 
 * @version 1.0 <br>
 *
 */
public interface BaseDao<T> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_mutimedia_album
	 *
	 * @mbggenerated Tue Mar 24 14:57:35 CST 2015
	 */
	public int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_mutimedia_album
	 *
	 * @mbggenerated Tue Mar 24 14:57:35 CST 2015
	 */
	public int insert(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_mutimedia_album
	 *
	 * @mbggenerated Tue Mar 24 14:57:35 CST 2015
	 */
	public int insertSelective(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_mutimedia_album
	 *
	 * @mbggenerated Tue Mar 24 14:57:35 CST 2015
	 */
	public T selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_mutimedia_album
	 *
	 * @mbggenerated Tue Mar 24 14:57:35 CST 2015
	 */
	public int updateByPrimaryKeySelective(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_mutimedia_album
	 *
	 * @mbggenerated Tue Mar 24 14:57:35 CST 2015
	 */
	public int updateByPrimaryKey(T record);

	public List<T> findByMulti(Map<String, Object> params);
	public List<T> findByMulti0(Map<String, Object> params);

	public T findById(String id);
}
