package com.topview.school.po;

public class ScoreStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_score_status.id
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_score_status.t_sc_school_id
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    private String tScSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_score_status.rank_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    private Integer rankStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_score_status.average_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    private Integer averageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_score_status.high_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    private Integer highScoreStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_score_status.id
     *
     * @return the value of t_sc_score_status.id
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_score_status.id
     *
     * @param id the value for t_sc_score_status.id
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_score_status.t_sc_school_id
     *
     * @return the value of t_sc_score_status.t_sc_school_id
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public String gettScSchoolId() {
        return tScSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_score_status.t_sc_school_id
     *
     * @param tScSchoolId the value for t_sc_score_status.t_sc_school_id
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public void settScSchoolId(String tScSchoolId) {
        this.tScSchoolId = tScSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_score_status.rank_status
     *
     * @return the value of t_sc_score_status.rank_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public Integer getRankStatus() {
        return rankStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_score_status.rank_status
     *
     * @param rankStatus the value for t_sc_score_status.rank_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public void setRankStatus(Integer rankStatus) {
        this.rankStatus = rankStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_score_status.average_status
     *
     * @return the value of t_sc_score_status.average_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public Integer getAverageStatus() {
        return averageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_score_status.average_status
     *
     * @param averageStatus the value for t_sc_score_status.average_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public void setAverageStatus(Integer averageStatus) {
        this.averageStatus = averageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_score_status.high_score_status
     *
     * @return the value of t_sc_score_status.high_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public Integer getHighScoreStatus() {
        return highScoreStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_score_status.high_score_status
     *
     * @param highScoreStatus the value for t_sc_score_status.high_score_status
     *
     * @mbggenerated Thu Apr 21 21:09:29 CST 2016
     */
    public void setHighScoreStatus(Integer highScoreStatus) {
        this.highScoreStatus = highScoreStatus;
    }
}