package com.topview.message.po;

public class PushKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_key.id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_key.apikey
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String apikey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_push_key.secretkey
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    private String secretkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_key.id
     *
     * @return the value of t_push_key.id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_key.id
     *
     * @param id the value for t_push_key.id
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_key.apikey
     *
     * @return the value of t_push_key.apikey
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_key.apikey
     *
     * @param apikey the value for t_push_key.apikey
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void setApikey(String apikey) {
        this.apikey = apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_push_key.secretkey
     *
     * @return the value of t_push_key.secretkey
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_push_key.secretkey
     *
     * @param secretkey the value for t_push_key.secretkey
     *
     * @mbggenerated Wed May 18 13:35:29 CST 2016
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey;
    }
}