package com.topview.multimedia.po;

import java.math.BigDecimal;
/**
 * 视频
 * 项目名称:com.topview.multimedia.po<br>
 * 
 * @author houwenjun<br>
 * 创建时间:Apr 11, 2015<br>
 */
public class MultimediaVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String id; 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String tMId; //所属视频库id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.name
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String name; //视频名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.description
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String description; //描述

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String comment; //备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.label
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String label; //标签

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Integer status; //状态

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.video_path
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String videoPath; //视频路径

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.size
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private BigDecimal size; //视频大小

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video.format
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String format; //视频格式

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.ID
     *
     * @return the value of t_mutimedia_video.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.ID
     *
     * @param id the value for t_mutimedia_video.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.t_m_ID
     *
     * @return the value of t_mutimedia_video.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.t_m_ID
     *
     * @param tMId the value for t_mutimedia_video.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.name
     *
     * @return the value of t_mutimedia_video.name
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.name
     *
     * @param name the value for t_mutimedia_video.name
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.description
     *
     * @return the value of t_mutimedia_video.description
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.description
     *
     * @param description the value for t_mutimedia_video.description
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.comment
     *
     * @return the value of t_mutimedia_video.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.comment
     *
     * @param comment the value for t_mutimedia_video.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.label
     *
     * @return the value of t_mutimedia_video.label
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.label
     *
     * @param label the value for t_mutimedia_video.label
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.status
     *
     * @return the value of t_mutimedia_video.status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.status
     *
     * @param status the value for t_mutimedia_video.status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.video_path
     *
     * @return the value of t_mutimedia_video.video_path
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.video_path
     *
     * @param videoPath the value for t_mutimedia_video.video_path
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.size
     *
     * @return the value of t_mutimedia_video.size
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public BigDecimal getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.size
     *
     * @param size the value for t_mutimedia_video.size
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setSize(BigDecimal size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video.format
     *
     * @return the value of t_mutimedia_video.format
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video.format
     *
     * @param format the value for t_mutimedia_video.format
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setFormat(String format) {
        this.format = format;
    }
}