package com.topview.multimedia.po;

import java.util.Date;
/**
 * 文章
 * 项目名称:com.topview.multimedia.po<br>
 * 
 * @author houwenjun<br>
 * 创建时间:Apr 11, 2015<br>
 */
public class MultimediaRichText {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String tMId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Date createTime; 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.context
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String context; //文章内容

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Integer status; //状态

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Integer type; // 类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.title
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String title; //标题

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.subtitle
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String subtitle; //副标题

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.titlephoto
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String titlephoto; //标题图片路径

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.summary
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String summary; //简介

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.essence
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Boolean essence; //是否“精华”

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_rich_text.top
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Boolean top; //是否置顶

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.ID
     *
     * @return the value of t_mutimedia_rich_text.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.ID
     *
     * @param id the value for t_mutimedia_rich_text.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.t_m_ID
     *
     * @return the value of t_mutimedia_rich_text.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.t_m_ID
     *
     * @param tMId the value for t_mutimedia_rich_text.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.create_time
     *
     * @return the value of t_mutimedia_rich_text.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.create_time
     *
     * @param createTime the value for t_mutimedia_rich_text.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.context
     *
     * @return the value of t_mutimedia_rich_text.context
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.context
     *
     * @param context the value for t_mutimedia_rich_text.context
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setContext(String context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.status
     *
     * @return the value of t_mutimedia_rich_text.status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.status
     *
     * @param status the value for t_mutimedia_rich_text.status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.type
     *
     * @return the value of t_mutimedia_rich_text.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.type
     *
     * @param type the value for t_mutimedia_rich_text.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.title
     *
     * @return the value of t_mutimedia_rich_text.title
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.title
     *
     * @param title the value for t_mutimedia_rich_text.title
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.subtitle
     *
     * @return the value of t_mutimedia_rich_text.subtitle
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.subtitle
     *
     * @param subtitle the value for t_mutimedia_rich_text.subtitle
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.titlephoto
     *
     * @return the value of t_mutimedia_rich_text.titlephoto
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getTitlephoto() {
        return titlephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.titlephoto
     *
     * @param titlephoto the value for t_mutimedia_rich_text.titlephoto
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setTitlephoto(String titlephoto) {
        this.titlephoto = titlephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.summary
     *
     * @return the value of t_mutimedia_rich_text.summary
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.summary
     *
     * @param summary the value for t_mutimedia_rich_text.summary
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.essence
     *
     * @return the value of t_mutimedia_rich_text.essence
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Boolean getEssence() {
        return essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.essence
     *
     * @param essence the value for t_mutimedia_rich_text.essence
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setEssence(Boolean essence) {
        this.essence = essence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_rich_text.top
     *
     * @return the value of t_mutimedia_rich_text.top
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_rich_text.top
     *
     * @param top the value for t_mutimedia_rich_text.top
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setTop(Boolean top) {
        this.top = top;
    }
}