package com.topview.multimedia.po;

import java.util.Date;
/**
 * 空间
 * 项目名称:com.topview.multimedia.po<br>
 * 
 * @author houwenjun<br>
 * 创建时间:Apr 11, 2015<br>
 */
public class MultimediaZone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_mutil_media_zone.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String id; //对应学校或班级id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_mutil_media_zone.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_mutil_media_zone.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String comment; //备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_mutil_media_zone.account_status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Integer accountStatus; //状态

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_mutil_media_zone.ID
     *
     * @return the value of t_mutimedia_mutil_media_zone.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_mutil_media_zone.ID
     *
     * @param id the value for t_mutimedia_mutil_media_zone.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_mutil_media_zone.create_time
     *
     * @return the value of t_mutimedia_mutil_media_zone.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_mutil_media_zone.create_time
     *
     * @param createTime the value for t_mutimedia_mutil_media_zone.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_mutil_media_zone.comment
     *
     * @return the value of t_mutimedia_mutil_media_zone.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_mutil_media_zone.comment
     *
     * @param comment the value for t_mutimedia_mutil_media_zone.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_mutil_media_zone.account_status
     *
     * @return the value of t_mutimedia_mutil_media_zone.account_status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_mutil_media_zone.account_status
     *
     * @param accountStatus the value for t_mutimedia_mutil_media_zone.account_status
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }
}