package com.topview.school.po;

public class AppraiseSubjectTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_subject_template.id
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_subject_template.subject
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_subject_template.word
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_subject_template.star
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    private String star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_appraise_subject_template.sign
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_subject_template.id
     *
     * @return the value of t_sc_appraise_subject_template.id
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_subject_template.id
     *
     * @param id the value for t_sc_appraise_subject_template.id
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_subject_template.subject
     *
     * @return the value of t_sc_appraise_subject_template.subject
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_subject_template.subject
     *
     * @param subject the value for t_sc_appraise_subject_template.subject
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_subject_template.word
     *
     * @return the value of t_sc_appraise_subject_template.word
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_subject_template.word
     *
     * @param word the value for t_sc_appraise_subject_template.word
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_subject_template.star
     *
     * @return the value of t_sc_appraise_subject_template.star
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_subject_template.star
     *
     * @param star the value for t_sc_appraise_subject_template.star
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public void setStar(String star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_appraise_subject_template.sign
     *
     * @return the value of t_sc_appraise_subject_template.sign
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_appraise_subject_template.sign
     *
     * @param sign the value for t_sc_appraise_subject_template.sign
     *
     * @mbggenerated Sun Jan 10 20:46:16 CST 2016
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

	@Override
	public String toString() {
		return "AppraiseSubjectTemplate [id=" + id + ", subject=" + subject + ", word=" + word + ", star=" + star
				+ ", sign=" + sign + "]";
	}
}