package com.topview.school.po;

public class ExceptUrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_except_url.id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_except_url.type
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_except_url.url
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_except_url.id
     *
     * @return the value of t_sc_except_url.id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_except_url.id
     *
     * @param id the value for t_sc_except_url.id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_except_url.type
     *
     * @return the value of t_sc_except_url.type
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_except_url.type
     *
     * @param type the value for t_sc_except_url.type
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_except_url.url
     *
     * @return the value of t_sc_except_url.url
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_except_url.url
     *
     * @param url the value for t_sc_except_url.url
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }
}