package com.topview.school.po;

import java.util.Date;


public class PageView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_page_view.id
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_page_view.ip
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_page_view.access_time
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    private Date accessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_page_view.url
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    private String url;
    
    /**
     * 
     */
    private String schoolId;
    
    private String userId;
    



	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(String schoolId) {
		this.schoolId = schoolId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_page_view.id
     *
     * @return the value of t_sc_page_view.id
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_page_view.id
     *
     * @param id the value for t_sc_page_view.id
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_page_view.ip
     *
     * @return the value of t_sc_page_view.ip
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_page_view.ip
     *
     * @param ip the value for t_sc_page_view.ip
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_page_view.access_time
     *
     * @return the value of t_sc_page_view.access_time
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_page_view.access_time
     *
     * @param accessTime the value for t_sc_page_view.access_time
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_page_view.url
     *
     * @return the value of t_sc_page_view.url
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_page_view.url
     *
     * @param url the value for t_sc_page_view.url
     *
     * @mbggenerated Sun Oct 04 14:23:45 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }
}