package com.topview.school.po;

public class Parent2Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent_student.student_id
     *
     * @mbggenerated Mon Jun 15 19:27:18 CST 2015
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_parent_student.parent_id
     *
     * @mbggenerated Mon Jun 15 19:27:18 CST 2015
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent_student.student_id
     *
     * @return the value of t_sc_parent_student.student_id
     *
     * @mbggenerated Mon Jun 15 19:27:18 CST 2015
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent_student.student_id
     *
     * @param studentId the value for t_sc_parent_student.student_id
     *
     * @mbggenerated Mon Jun 15 19:27:18 CST 2015
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_parent_student.parent_id
     *
     * @return the value of t_sc_parent_student.parent_id
     *
     * @mbggenerated Mon Jun 15 19:27:18 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_parent_student.parent_id
     *
     * @param parentId the value for t_sc_parent_student.parent_id
     *
     * @mbggenerated Mon Jun 15 19:27:18 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
}