package com.topview.school.po;

public class RecordUrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_record_url.id
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_record_url.type
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_record_url.url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_record_url.id
     *
     * @return the value of t_sc_record_url.id
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_record_url.id
     *
     * @param id the value for t_sc_record_url.id
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_record_url.type
     *
     * @return the value of t_sc_record_url.type
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_record_url.type
     *
     * @param type the value for t_sc_record_url.type
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_record_url.url
     *
     * @return the value of t_sc_record_url.url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_record_url.url
     *
     * @param url the value for t_sc_record_url.url
     *
     * @mbggenerated Sun Jan 17 09:19:51 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }
}