package com.topview.school.po;

public class UserSalt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_salt.id
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_salt.salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_salt.user_id
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_salt.id
     *
     * @return the value of user_salt.id
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_salt.id
     *
     * @param id the value for user_salt.id
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_salt.salt
     *
     * @return the value of user_salt.salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_salt.salt
     *
     * @param salt the value for user_salt.salt
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_salt.user_id
     *
     * @return the value of user_salt.user_id
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_salt.user_id
     *
     * @param userId the value for user_salt.user_id
     *
     * @mbggenerated Sun May 22 14:25:22 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}