package com.topview.school.po;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    private String id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.school_id
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    @NotNull
    @Size(max=25)
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.description
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    @NotNull
    @Size(max=64)
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.available
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.school_id
     *
     * @return the value of role.school_id
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.school_id
     *
     * @param schoolId the value for role.school_id
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role
     *
     * @return the value of role.role
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role
     *
     * @param role the value for role.role
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.description
     *
     * @return the value of role.description
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.description
     *
     * @param description the value for role.description
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.available
     *
     * @return the value of role.available
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.available
     *
     * @param available the value for role.available
     *
     * @mbggenerated Sun Oct 25 15:58:42 CST 2015
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}