package com.topview.school.po;

public class Teacher2RoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_teacher_role.t_sc_teacher_id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    private String tScTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sc_teacher_role.t_sc_role_id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    private String tScRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_teacher_role.t_sc_teacher_id
     *
     * @return the value of t_sc_teacher_role.t_sc_teacher_id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public String gettScTeacherId() {
        return tScTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_teacher_role.t_sc_teacher_id
     *
     * @param tScTeacherId the value for t_sc_teacher_role.t_sc_teacher_id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public void settScTeacherId(String tScTeacherId) {
        this.tScTeacherId = tScTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sc_teacher_role.t_sc_role_id
     *
     * @return the value of t_sc_teacher_role.t_sc_role_id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public String gettScRoleId() {
        return tScRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sc_teacher_role.t_sc_role_id
     *
     * @param tScRoleId the value for t_sc_teacher_role.t_sc_role_id
     *
     * @mbggenerated Wed Jul 15 21:58:37 CST 2015
     */
    public void settScRoleId(String tScRoleId) {
        this.tScRoleId = tScRoleId;
    }
}