package com.topview.multimedia.po;

import java.util.Date;

public class MultimediaAlbum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.ID
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.t_m_ID
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private String tMId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.name
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.comment
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.description
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.create_time
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.photo_count2
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private Integer photoCount2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.type
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.update_time
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_album.cover_path
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    private String coverPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.ID
     *
     * @return the value of t_mutimedia_album.ID
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.ID
     *
     * @param id the value for t_mutimedia_album.ID
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.t_m_ID
     *
     * @return the value of t_mutimedia_album.t_m_ID
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.t_m_ID
     *
     * @param tMId the value for t_mutimedia_album.t_m_ID
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.name
     *
     * @return the value of t_mutimedia_album.name
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.name
     *
     * @param name the value for t_mutimedia_album.name
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.comment
     *
     * @return the value of t_mutimedia_album.comment
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.comment
     *
     * @param comment the value for t_mutimedia_album.comment
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.description
     *
     * @return the value of t_mutimedia_album.description
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.description
     *
     * @param description the value for t_mutimedia_album.description
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.create_time
     *
     * @return the value of t_mutimedia_album.create_time
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.create_time
     *
     * @param createTime the value for t_mutimedia_album.create_time
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.photo_count2
     *
     * @return the value of t_mutimedia_album.photo_count2
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public Integer getPhotoCount2() {
        return photoCount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.photo_count2
     *
     * @param photoCount2 the value for t_mutimedia_album.photo_count2
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setPhotoCount2(Integer photoCount2) {
        this.photoCount2 = photoCount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.type
     *
     * @return the value of t_mutimedia_album.type
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.type
     *
     * @param type the value for t_mutimedia_album.type
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.update_time
     *
     * @return the value of t_mutimedia_album.update_time
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.update_time
     *
     * @param updateTime the value for t_mutimedia_album.update_time
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_album.cover_path
     *
     * @return the value of t_mutimedia_album.cover_path
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public String getCoverPath() {
        return coverPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_album.cover_path
     *
     * @param coverPath the value for t_mutimedia_album.cover_path
     *
     * @mbggenerated Wed Jul 27 13:20:30 CST 2016
     */
    public void setCoverPath(String coverPath) {
        this.coverPath = coverPath;
    }
}