package com.topview.multimedia.po;

import java.util.Date;
/**
 * 视频库
 * 项目名称:com.topview.multimedia.po<br>
 * 
 * @author houwenjun<br>
 * 创建时间:Apr 11, 2015<br>
 */
public class MultimediaVideoLibrary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String tMId; //所属多媒体空间id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.name2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String name2; //视频库名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String comment; //备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.description2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private String description2; //描述

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.photo_count2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Integer photoCount2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mutimedia_video_libary.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.ID
     *
     * @return the value of t_mutimedia_video_libary.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.ID
     *
     * @param id the value for t_mutimedia_video_libary.ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.t_m_ID
     *
     * @return the value of t_mutimedia_video_libary.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String gettMId() {
        return tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.t_m_ID
     *
     * @param tMId the value for t_mutimedia_video_libary.t_m_ID
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void settMId(String tMId) {
        this.tMId = tMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.name2
     *
     * @return the value of t_mutimedia_video_libary.name2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.name2
     *
     * @param name2 the value for t_mutimedia_video_libary.name2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setName2(String name2) {
        this.name2 = name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.comment
     *
     * @return the value of t_mutimedia_video_libary.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.comment
     *
     * @param comment the value for t_mutimedia_video_libary.comment
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.description2
     *
     * @return the value of t_mutimedia_video_libary.description2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public String getDescription2() {
        return description2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.description2
     *
     * @param description2 the value for t_mutimedia_video_libary.description2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setDescription2(String description2) {
        this.description2 = description2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.create_time
     *
     * @return the value of t_mutimedia_video_libary.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.create_time
     *
     * @param createTime the value for t_mutimedia_video_libary.create_time
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.photo_count2
     *
     * @return the value of t_mutimedia_video_libary.photo_count2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Integer getPhotoCount2() {
        return photoCount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.photo_count2
     *
     * @param photoCount2 the value for t_mutimedia_video_libary.photo_count2
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setPhotoCount2(Integer photoCount2) {
        this.photoCount2 = photoCount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mutimedia_video_libary.type
     *
     * @return the value of t_mutimedia_video_libary.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mutimedia_video_libary.type
     *
     * @param type the value for t_mutimedia_video_libary.type
     *
     * @mbggenerated Tue Mar 24 14:57:35 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }
}