package com.topview.multimedia.po;

public class PostAccessory {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_post_accessory.id
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_post_accessory.t_mutimedia_post_id
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	private String tMutimediaPostId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_mutimedia_post_accessory.url
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_mutimedia_post_accessory.id
	 *
	 * @return the value of t_mutimedia_post_accessory.id
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */

	private int orders;

	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_mutimedia_post_accessory.id
	 *
	 * @param id
	 *            the value for t_mutimedia_post_accessory.id
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * t_mutimedia_post_accessory.t_mutimedia_post_id
	 *
	 * @return the value of t_mutimedia_post_accessory.t_mutimedia_post_id
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	public String gettMutimediaPostId() {
		return tMutimediaPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * t_mutimedia_post_accessory.t_mutimedia_post_id
	 *
	 * @param tMutimediaPostId
	 *            the value for t_mutimedia_post_accessory.t_mutimedia_post_id
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	public void settMutimediaPostId(String tMutimediaPostId) {
		this.tMutimediaPostId = tMutimediaPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_mutimedia_post_accessory.url
	 *
	 * @return the value of t_mutimedia_post_accessory.url
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_mutimedia_post_accessory.url
	 *
	 * @param url
	 *            the value for t_mutimedia_post_accessory.url
	 *
	 * @mbggenerated Tue Jul 21 00:13:24 CST 2015
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	public int getorders() {
		return orders;
	}

	public void setorders(int orders) {
		this.orders = orders;
	}

}